name: Build archlinux kernel
on:
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string

env:
  _processor_opt: "x86-64"
  _git_mirror: "gregkh"
  PKGDEST: "/tmp/linux-tkt"
  _debugdisable: "true"
  _noccache: "true"
  _STRIP: "true"
  _kernel_on_diet: "false"
  _kernel_work_folder: "/tmp"
  _kernel_source_folder: "/tmp"
  # _modprobeddb: "true"
  _modprobeddb_db_path: ${{ github.workspace }}/modprobed.db
  _nofallback: "false"

jobs:
  build-kernel:
    env:
      _cpusched: ${{ inputs._cpusched }}

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Update mirrorlist
        run: |
          pacman -Sy --noconfirm reflector rsync curl wget aria2
          reflector --fastest 10 --verbose --country US --protocol rsync,https,http --latest 10 --age 1 --sort rate --save /etc/pacman.d/mirrorlist

      - name: Install dependencies
        run: pacman -Syu --noconfirm git clang llvm lld base-devel sudo bison xmlto docbook-xsl inetutils bc libelf pahole patchutils flex python-sphinx python-sphinx_rtd_theme graphviz imagemagick git cpio perl tar xz schedtool coreutils kmod initramfs pahole

      - name: Checkout TKT
        uses: actions/checkout@v4

      - name: Prepare for makepkg
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp

      - name: Compile Kernel
        run: su --preserve-environment user -c "yes '' | makepkg --noconfirm -s"

      - name: rename kernel config
        run: mv kernelconfig.new kernelconfig.arch.${{ env._cpusched }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: arch-kernel-packages-${{ env._cpusched }}
          path: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt
