name: Build archlinux kernel
on:
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string


env:
  _processor_opt: "generic"
  _git_mirror: "gregkh"
  PKGDEST: "/tmp/TKT"
  _debugdisable: "true"
  _noccache: "false"
  _STRIP: "true"
  _kernel_on_diet: "false"
  _kernel_work_folder: "/tmp"
  _kernel_source_folder: "/tmp"
  # _modprobeddb: "true"
  _modprobeddb_db_path: ${{ github.workspace }}/modprobed.db



jobs:
  build-kernel:
    env:
      _cpusched: ${{ inputs._cpusched }}

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:

      - name: Pacman prep
        run: pacman -Syu --noconfirm git base-devel clang llvm lld bison xmlto docbook-xsl inetutils bc libelf pahole patchutils flex python-sphinx python-sphinx_rtd_theme graphviz imagemagick cpio perl tar xz wget schedtool

      - name: Checkout main
        uses: actions/checkout@v4

      - name: Compile Kernel
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          su user -c "yes '' | makepkg --noconfirm -sC"

      - name: rename kernel config
        run: mv kernelconfig.new "kernelconfig.arch.${{ env._cpusched }}.txt"

      - uses: actions/upload-artifact@v4
        with:
          name: arch-kernel-packages-${{ env._cpusched }}
          path: |
            ${{ env.PKGDEST }}/*.pkg.tar*
            kernelconfig*.txt
