name: Lint Code Base
on:
  push:
  pull_request:
jobs:
  build_ubuntu-latest:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #build_self-hosted:
  #  name: Lint Code Base
  #  runs-on: self-hosted
  #  steps:
  #    - name: Checkout Code
  #      uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0
  #    - name: Lint Code Base
  #      uses: github/super-linter/slim@v7
  #      env:
  #        VALIDATE_ALL_CODEBASE: true
  #        VALIDATE_YAML: true
  #        VALIDATE_GITHUB_ACTIONS: true
  #        VALIDATE_JSON: true
  #        VALIDATE_JAVASCRIPT_ES: true
  #        DEFAULT_BRANCH: master
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
