name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        cache: 'npm'

    - name: Cache NPM dependencies
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('.github/workflows/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Run linter
      run: npm run lint
