name: Lint Code Base

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Linter
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: ${{ runner.os }}-linter-${{ hashFiles('**/*.sh') }}
        restore-keys: |
          ${{ runner.os }}-linter-
          ${{ runner.os }}-

    - name: Run Super Linter
      uses: github/super-linter@v3
      with:
        args: --no-color
