name: Build SUSE kernel
on:
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string
      compiler:
        required: true
        type: string

env:
  _processor_opt: "x86-64"
  _distro: "Suse"
  _git_mirror: "gregkh"
  _logging_use_script: "no"
  _install_after_building: "no"
  _debugdisable: "true"
  _noccache: "true"
  _STRIP: "true"
  _kernel_on_diet: "true"
  _nofallback: "false"

jobs:
  build-kernel:
    env:
      _cpusched: ${{ inputs._cpusched }}
      compiler: ${{ inputs.compiler }}

    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest

    steps:
      - name: Add Python Modules repo and import GPG key
        run: |
          zypper --non-interactive addrepo --refresh \
            https://download.opensuse.org/repositories/devel:languages:python/openSUSE_Tumbleweed/devel:languages:python.repo || true
          rpm --import https://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Tumbleweed/repodata/repomd.xml.key || true
          zypper --gpg-auto-import-keys refresh

      - name: Install dependencies
        run: |
          zypper refresh
          zypper --non-interactive install \
            bc bison ccache clang curl dwarves flex gcc-c++ gawk git hostname \
            kernel-devel libXi-devel libuuid-devel lld llvm lz4 make ncurses-devel libnuma-devel \
            libopenssl-devel libdw-devel patchutils perl pesign python3 python311-devel python311-pip \
            libqt5-qtbase-devel rpm-build rsync wget zstd \
            libelf-devel systemd-devel
          zypper clean -a

      - name: Checkout TKT
        uses: actions/checkout@v4

      - name: Adjust compiler and compile Kernel
        env:
          _cpusched: ${{ inputs._cpusched }}
          compiler: ${{ inputs.compiler }}
        run: |
          git config --global --add safe.directory "$(pwd)"
          if [ "${{ inputs.compiler }}" = "llvm" ] || [ "${{ inputs.compiler }}" = "clang" ]; then
            export KCFLAGS="$KCFLAGS -Wold-style-declaration"
          fi
          sed -i 's/^_distro=".*"/_distro="Suse"/' customization.cfg
          sed -i 's/^_compiler=".*"/_compiler="${{ inputs.compiler }}"/' customization.cfg
          set +o pipefail
          _distro="Suse" _compiler="${{ inputs.compiler }}" yes '' | ./install.sh install || true
          set -o pipefail

      - name: Rename RPM files to $arch-linux format
        run: |
          arch=$(uname -m)
          for file in RPMS/kernel*.rpm; do
            base=$(basename "$file")
            mv "$file" "RPMS/SUSE-linux-${arch}-${base#kernel-}"
          done

      - name: Package RPM files
        run: |
          tar czf SUSE-linux-${{ env._cpusched }}-${{ inputs.compiler }}.tar.gz RPMS/*.rpm

      - uses: actions/upload-artifact@v4
        with:
          name: suse-kernel-packages-${{ env._cpusched }}-${{ inputs.compiler }}
          path: SUSE-linux-*.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: "SUSE Kernel Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: RPMS/SUSE-linux-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
